feat: add topic and qotd matching
CS3219-AY2223S1/cs3219-project-ay2223s1-g42 pull request #118
Opened 2022-11-02 22:25 UTC by aidanaden

closes #117

2022-11-04 15:49 UTC, yusufaine requested changes
One small change and should be good!

2022-11-04 15:49 UTC, yusufaine commented on frontend/src/pages/room/[id].tsx
> +          `/question/summary?topics=${room?.topics.join(",")}`
```suggestion
          `/question/summary?topicTags=${room?.topics.join(",")}`
```

2022-11-04 15:49 UTC, yusufaine commented on frontend/src/pages/room/[id].tsx
> +          `/question/summary?topics=${room?.topics.join(",")}`
```suggestion
          `/question/summary?topicTags=${room?.topics.join(",")}`
```

2022-11-05 13:26 UTC, ngjunkang reviewed
tested: qotd not working yet

2022-11-05 13:46 UTC, ngjunkang approved these changes
LGTM

2022-11-05 14:39 UTC, blaketingyu approved these changes
LGTM!

2022-11-06 13:36 UTC, yusufaine approved these changes
LGTM! Only left the small nit on topic tags

2022-11-06 13:37 UTC, merged