feat: backend history service
CS3219-AY2223S1/cs3219-project-ay2223s1-g42 pull request #119
Opened 2022-11-04 07:54 UTC by yusufaine

2022-11-05 17:41 UTC, aidanaden approved these changes

2022-11-05 18:15 UTC, ngjunkang requested changes

2022-11-05 18:15 UTC, ngjunkang commented on shared/src/models/userhistory.ts
> +  title: z.string(),
I think we need to add title to schema and SELECT right?

2022-11-06 11:04 UTC, ngjunkang approved these changes
LGTM

2022-11-06 13:14 UTC, merged

2022-11-06 13:17 UTC, blaketingyu approved these changes