Fix cookie options for local and prod
CS3219-AY2223S1/cs3219-project-ay2223s1-g42 pull request #120
Opened 2022-11-05 16:40 UTC by ngjunkang

Now backend prod needs to have a new env variable as follows, `NEST_ENV=prod`, optional for local environment

closes #106.

2022-11-05 17:45 UTC, aidanaden requested changes

2022-11-05 17:45 UTC, aidanaden commented on backend/src/config/options.ts
> +const PRODUCTION = process.env.NEST_ENV === "prod";
think might be better to use the `FRONTEND_URL` env variable to determine if it's production or not (if `FRONTEND_URL.includes("localhost") ? "dev" : "prod"`)

2022-11-05 18:25 UTC, aidanaden approved these changes

2022-11-06 12:48 UTC, blaketingyu approved these changes

2022-11-06 13:15 UTC, merged